### ISSUE TITLE
install-kubeadm.sh里wget会遇到Unable to establish SSL connection错误

### ISSUE THREAD

**Issue by once2019** [huweihuang/kubeadm-scripts#3]
install-kubeadm.sh里wget会遇到Unable to establish SSL connection错误，建议脚本加上参数：--no-check-certificate

安装脚本大概率会遇到重复执行的情况，在下载文件之前加上-f判断是否已有文件存在的情况，避免重复下载安装

**Comment by huweihuang** [comment]
谢谢，如果感兴趣可以帮忙提一个pr 修复一下。
